// LOCAL HOST
### Get All Users
GET http://localhost:3000/users
### Get Individual Users
### 1st
GET http://localhost:3000/users/672d184978e5120d9aede4e6
### 2nd
GET http://localhost:3000/users/672d19c378e5120d9aede4e7
### 3rd
GET http://localhost:3000/users/672d1a3e78e5120d9aede4e8
### Create User
POST http://localhost:3000/users
Content-Type: application/json

{
    "email":"testNewGuy1@fakeemail.com",
    "firstname":"New",
    "lastname":"Guy",
    "favcolor":"Blue",
    "birthday":"04-04-1980"
}

### Update User
PUT http://localhost:3000/users/672d184978e5120d9aede4e6
Content-Type: application/json

{
    "email":"starsagent007@fakeemail.com",
    "firstname":"Jill",
    "lastname":"Valentine",
    "favcolor":"Pink",
    "birthday":"03-22-1996"
}

### Update User Back to Original
PUT http://localhost:3000/users/672d184978e5120d9aede4e6
Content-Type: application/json

{
    "email":"jillstars@fakeemail.com",
    "firstname":"Jill",
    "lastname":"Valentine",
    "favcolor":"Pink",
    "birthday":"03-22-1996"
}

### Delete User - (Make sure to replace the id)
DELETE http://localhost:3000/users/67354065f944cdd73069a66d

// PRODUCTION
### Get All Users
GET https://cs-cse341-project1.onrender.com/users
### Get Individual Users
### 1st
GET https://cs-cse341-project1.onrender.com/users/672d184978e5120d9aede4e6
### 2nd
GET https://cs-cse341-project1.onrender.com/users/672d19c378e5120d9aede4e7
### 3rd
GET https://cs-cse341-project1.onrender.com/users/672d1a3e78e5120d9aede4e8
### Create User
POST https://cs-cse341-project1.onrender.com/users
Content-Type: application/json

{
    "email":"testNewGuy1@fakeemail.com",
    "firstname":"New",
    "lastname":"Guy",
    "favcolor":"Blue",
    "birthday":"04-04-1980"
}

### Update User
PUT https://cs-cse341-project1.onrender.com/users/672d184978e5120d9aede4e6
Content-Type: application/json

{
    "email":"starsagent007@fakeemail.com",
    "firstname":"Jill",
    "lastname":"Valentine",
    "favcolor":"Pink",
    "birthday":"03-22-1996"
}

### Update User Back to Original
PUT https://cs-cse341-project1.onrender.com/users/672d184978e5120d9aede4e6
Content-Type: application/json

{
    "email":"jillstars@fakeemail.com",
    "firstname":"Jill",
    "lastname":"Valentine",
    "favcolor":"Pink",
    "birthday":"03-22-1996"
}

### Delete User - (Make sure to replace the id)
DELETE https://cs-cse341-project1.onrender.com/users/67354065f944cdd73069a66d